Fix code smells
FlowingCode/ChipFieldAddon pull request #23
Opened 2020-12-14 13:49 UTC by ngonzalezpazFC

Add serialization test

2020-12-14 15:26 UTC, javier-godoy requested changes
Address the other code smells mentioned in https://sonarcloud.io/project/issues?id=FlowingCode_ChipFieldAddon&resolved=false&types=CODE_SMELL

2020-12-14 15:26 UTC, javier-godoy commented on src/main/java/com/flowingcode/vaadin/addons/chipfield/ChipField.java
> +	@SuppressWarnings("squid:S1186")
It's not clear why the method does not have a method body: is it an unintentional omission? is it not supported? is it an intentionally-blank override? Remove the `@SuppressWarnings`

2020-12-23 20:17 UTC, javier-godoy requested changes
Please rebase (because this PR was based on the old master). It's not clear which of the commits belong to this PR.

2020-12-28 13:35 UTC, javier-godoy commented
BTW 2ca18b3: `feat: implement Serializable`

2020-12-28 15:04 UTC, ngonzalezpazFC commented
> 
> 
> Please rebase (because this PR was based on the old master). It's not clear which of the commits belong to this PR.

Should this [commit ](https://github.com/FlowingCode/ChipFieldAddon/pull/23/commits/2903eea28db3db4cd9154443b0d28dfbeeb0307c)message be "feat: implement Serializable"?

2021-01-04 12:29 UTC, javier-godoy commented
> Should this commit (2903eea2) message be "feat: implement Serializable"?
No, because the commit only adds the serialization test (the component was already serializable)

2021-01-13 19:14 UTC, javier-godoy approved these changes

2021-01-13 19:14 UTC, merged