Fix readonly mode
FlowingCode/ChipFieldAddon pull request #56
Opened 2021-07-29 18:55 UTC by paodb

Close #40

2021-07-29 19:46 UTC, javier-godoy approved these changes

2021-07-29 19:48 UTC, javier-godoy requested changes
a6b68ac6 correct style changes introduced in a28ae0ae, please squash

2021-08-02 14:15 UTC, paodb commented
Requested changes done.

2021-08-02 14:17 UTC, javier-godoy approved these changes

2021-08-02 14:17 UTC, merged